services:
  currency-exchange:
    image: exchange
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka
    deploy:
      resources:
        limits:
          memory: 700m
  currency-conversion:
    image: conversion
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka
    deploy:
      resources:
        limits:
          memory: 700m
  api-gateway:
    image: gateway
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka
    deploy:
      resources:
        limits:
          memory: 700m
  naming-server:
    image: nameserver
    ports:
      - "8761:8761"
    networks:
      - currency-network
    deploy:
      resources:
        limits:
          memory: 700m
networks:
  currency-network:
