version: '3.8'

services:
  currency-exchange:
    build: 
      context: ./currency-exchange-service
      dockerfile: Dockerfile
    image: currency-exchange-img
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      - SPRING_APPLICATION_NAME=currency-exchange
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
    deploy:
      resources:
        limits:
          memory: 700m

  currency-conversion:
    build: 
      context: ./currency-conversion-service
      dockerfile: Dockerfile
    image: currency-conversion-img
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      - SPRING_APPLICATION_NAME=currency-conversion
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
    deploy:
      resources:
        limits:
          memory: 700m

  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api-gateway-img
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
    deploy:
      resources:
        limits:
          memory: 700m

  naming-server:
    build: 
      context: ./naming-server
      dockerfile: Dockerfile
    image: naming-server-img
    ports:
      - "8761:8761"
    networks:
      - currency-network
    deploy:
      resources:
        limits:
          memory: 700m

  # MICROSSERVIÇO A (Relatório)
  currency-report:
    build:
      context: ./currency-report
      dockerfile: Dockerfile
    image: currency-report-img
    ports:
      # Mapeia 8200 (Seu PC) -> 8080 (Container Spring Boot)
      - "8200:8080" 
    networks:
      - currency-network
    depends_on:
      - naming-server
      - currency-exchange
    environment:
      - SPRING_APPLICATION_NAME=currency-report
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
    deploy:
      resources:
        limits:
          memory: 700m

  # MICROSSERVIÇO B (Histórico) - NOVO!
  currency-history:
    build:
      context: ./currency-history
      dockerfile: Dockerfile
    image: currency-history-img
    ports:
      # Mapeia 8300 (Seu PC) -> 8080 (Container Spring Boot)
      - "8300:8080"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      - SPRING_APPLICATION_NAME=currency-history
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
    deploy:
      resources:
        limits:
          memory: 700m

networks:
  currency-network: